---
services:
  ocis:
    depends_on:
      dicomviewer-init:
        condition: service_completed_successfully

  dicomviewer-init:
    image: owncloud/web-app-dicom-viewer:latest
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/dicom-viewer/ /apps"]
